# Generated by Django 3.1.3 on 2020-11-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='my_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
