# Generated by Django 3.1.3 on 2020-12-03 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('furnapp', '0002_customer_my_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='my_name',
            new_name='contact_no',
        ),
        migrations.RemoveField(
            model_name='category',
            name='product_id',
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('sofa', 'sofa'), ('single beds', 'single beds'), ('double beds', 'double beds'), ('side tables', 'side tables'), ('double door wardrobe', 'double door wardrobe'), ('triple door wardrobe', 'triple door wardrobe')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furnapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='furnapp.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user_name',
            field=models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furnapp.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'accepted'), ('not accepted', 'not accepted'), ('delivered', 'delivered'), ('on process', 'on process')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_bill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
