# Generated by Django 3.1.3 on 2020-12-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0003_auto_20201203_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_num',
        ),
        migrations.AlterField(
            model_name='ordered_item',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
