# Generated by Django 3.1.3 on 2020-12-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0006_auto_20201214_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
