# Generated by Django 3.1.3 on 2020-12-21 09:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0009_auto_20201221_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='review',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='furnapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='date_enter',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
