# Generated by Django 3.1.2 on 2020-12-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnapp', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
